In [1]:
import torch
import numpy as np

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.5057, -0.0503,  1.6481],
        [ 0.6485,  0.5547, -0.2404]], requires_grad=True)
tensor([0.2337, 0.3968], requires_grad=True)


In [6]:
def model(x):
    return x @ w.t() + b

In [7]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 30.8127,  74.5682],
        [ 55.2630,  92.8425],
        [ 45.0818, 117.2089],
        [  7.4667,  81.5034],
        [ 75.8744,  81.5710]], grad_fn=<AddBackward0>)


In [8]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [10]:
# Train for 100 epochs
for i in range(500):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [11]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(53.2168, grad_fn=<DivBackward0>)


In [12]:
# Predictions
preds

tensor([[ 56.7260,  71.2849],
        [ 87.5038,  95.8914],
        [107.3530, 142.2593],
        [ 18.8684,  41.7567],
        [112.4723, 108.1350]], grad_fn=<AddBackward0>)

In [13]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

## Using Builtins

In [14]:
import torch.nn as nn
import torch
import numpy as np

In [15]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [16]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [17]:
from torch.utils.data import TensorDataset

In [18]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [19]:
from torch.utils.data import DataLoader

In [20]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [21]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 88., 134.,  59.],
        [ 87., 135.,  57.],
        [ 87., 134.,  58.],
        [ 91.,  87.,  65.],
        [ 73.,  66.,  44.]])
tensor([[118., 132.],
        [118., 134.],
        [119., 133.],
        [ 80., 102.],
        [ 57.,  69.]])


In [22]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.1174,  0.5007,  0.1849],
        [-0.5129,  0.2805, -0.1496]], requires_grad=True)
Parameter containing:
tensor([-0.2357,  0.3589], requires_grad=True)


In [23]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.1174,  0.5007,  0.1849],
         [-0.5129,  0.2805, -0.1496]], requires_grad=True),
 Parameter containing:
 tensor([-0.2357,  0.3589], requires_grad=True)]

In [24]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 32.6913, -24.7223],
        [ 44.9753, -31.2053],
        [ 67.3697, -15.3547],
        [ 16.1595, -45.4305],
        [ 52.6733, -18.5751],
        [ 32.0731, -25.5157],
        [ 44.6594, -31.6354],
        [ 67.4372, -16.0172],
        [ 16.7777, -44.6371],
        [ 52.9756, -18.2117],
        [ 32.3754, -25.1523],
        [ 44.3571, -31.9987],
        [ 67.6856, -14.9247],
        [ 15.8573, -45.7938],
        [ 53.2915, -17.7817]], grad_fn=<AddmmBackward>)

In [25]:
# Import nn.functional
import torch.nn.functional as F

In [26]:
# Define loss function
loss_fn = F.mse_loss

In [27]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(8126.7710, grad_fn=<MseLossBackward>)


In [28]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [29]:
from tqdm import tqdm

In [30]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in tqdm(range(num_epochs)):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print(' | Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [31]:
fit(100, model, loss_fn, opt, train_dl)

  0%|          | 0/100 [00:00<?, ?it/s] | Epoch [10/100], Loss: 135.6901
 | Epoch [20/100], Loss: 95.8522
 | Epoch [30/100], Loss: 57.8592
 | Epoch [40/100], Loss: 48.5422
 | Epoch [50/100], Loss: 52.4255
 | Epoch [60/100], Loss: 26.4296
 | Epoch [70/100], Loss: 23.9433
 | Epoch [80/100], Loss: 34.0205
100%|██████████| 100/100 [00:00<00:00, 1591.42it/s] | Epoch [90/100], Loss: 25.7723
 | Epoch [100/100], Loss: 31.0401



In [32]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 57.7405,  71.1840],
        [ 80.4911,  97.1900],
        [120.7696, 139.3987],
        [ 25.1575,  41.3908],
        [ 96.5754, 110.6071],
        [ 56.5483,  70.0761],
        [ 80.0081,  96.6412],
        [120.9062, 139.6577],
        [ 26.3497,  42.4986],
        [ 97.2847, 111.1662],
        [ 57.2576,  70.6352],
        [ 79.2988,  96.0822],
        [121.2525, 139.9475],
        [ 24.4482,  40.8317],
        [ 97.7677, 111.7150]], grad_fn=<AddmmBackward>)

In [33]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [34]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[53.9672, 67.4615]], grad_fn=<AddmmBackward>)