In [2]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1,2,3],[4,5,6]],requires_grad=True, device=device,dtype=torch.float32)

In [3]:
print(my_tensor)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.dtype)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
cpu
torch.Size([2, 3])
torch.float32
True


In [10]:
#Other Initialization Methods
a = torch.empty(size=(3,3))
b = torch.zeros(size=(3,3))
c = torch.ones(size=(3,3))
d = torch.eye(3)
e = torch.rand(size=(3,3))
f = torch.arange(start=0,end=5,step=1)
g = torch.linspace(start=0.1,end=1,steps=10)
h = torch.empty(size = (1,5)).normal_(mean=0,std=1)
i = torch.empty(size=(1,5)).uniform_(0,1)
j = torch.diag(torch.ones(3))

In [11]:
print(a,b,c,d,e,f,g,h,i,j,sep='\n')

tensor([[1.4013e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[0.6912, 0.2946, 0.0724],
        [0.9598, 0.3494, 0.1252],
        [0.4090, 0.4583, 0.4536]])
tensor([0, 1, 2, 3, 4])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([[-0.6392,  0.1930,  0.5493,  1.0578, -1.1686]])
tensor([[0.5906, 0.4993, 0.7328, 0.8907, 0.9444]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [13]:
#Type Conversion
tensorx = torch.arange(4)
print(tensorx.dtype)
print(tensorx.bool().dtype)
print(tensorx.short().dtype)
print(tensorx.long().dtype)
print(tensorx.half().dtype)
print(tensorx.float().dtype)
print(tensorx.double().dtype)

torch.int64
torch.bool
torch.int16
torch.int64
torch.float16
torch.float32
torch.float64


In [14]:
#Tensor <-> Numpy
import numpy as np
np_array = np.array((5,5))
print(np_array)
tensornp = torch.from_numpy(np_array)
print(tensornp)
np_array_back = tensornp.numpy()
print(np_array_back)

[5 5]
tensor([5, 5])
[5 5]


In [25]:
#Math Operation
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])

print(x+y)
print(x.add(y))

print(x-y)
print(x.subtract(y))

print(x/y)
print(x.true_divide(y))

print(x*y)
print(x.multiply(y))

print(x+y)
print(x.add(y))

#inplace operations
t = torch.zeros(3)
t.add_(x)
t+=x

#exponentiations
z = x.pow(2)
z=x**2
print(z)

z=x<0
z=x>0
print(z)

tensor([5, 7, 9])
tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([-3, -3, -3])
tensor([0.2500, 0.4000, 0.5000])
tensor([0.2500, 0.4000, 0.5000])
tensor([ 4, 10, 18])
tensor([ 4, 10, 18])
tensor([5, 7, 9])
tensor([5, 7, 9])
tensor([1, 4, 9])
tensor([True, True, True])


In [27]:
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm(x1,x2)
x4 = x1.mm(x2)
print(x3,x4,sep='\n')

tensor([[0.9643, 0.7507, 0.4912],
        [0.9863, 0.7888, 0.4897]])
tensor([[0.9643, 0.7507, 0.4912],
        [0.9863, 0.7888, 0.4897]])


In [29]:
#matrix Exponensiation
matrix_exp = torch.rand(5,5)
print(matrix_exp.matrix_power(3))

tensor([[5.5600, 3.0721, 1.9603, 5.0415, 4.6178],
        [6.6688, 4.0289, 2.7782, 5.6912, 5.6479],
        [6.1679, 3.9889, 3.0391, 5.0202, 5.2341],
        [6.8031, 3.8873, 2.5555, 6.1129, 5.6835],
        [6.4420, 3.8293, 2.6775, 5.5868, 5.4227]])


In [32]:
#element wise multipication
z = x*y
print(z)
z = torch.dot(x,y)
print(z)

tensor([ 4, 10, 18])
tensor(32)


In [33]:
#Batch Matrix Multiplication
batch,n,m,p= 32,10,20,30
tensor1 = torch.rand((batch,n,m))
tensor2 = torch.rand((batch,m,p))
outbmm = torch.bmm(tensor1,tensor2)
print(outbmm)

tensor([[[3.8725, 4.5113, 4.0529,  ..., 4.6497, 4.2341, 4.3604],
         [4.2129, 4.4074, 4.5729,  ..., 4.6817, 4.2524, 3.4772],
         [5.8480, 5.7207, 6.6015,  ..., 6.5405, 5.5734, 5.9854],
         ...,
         [5.4217, 6.4659, 5.6399,  ..., 6.4945, 5.5891, 5.4505],
         [3.9702, 4.2997, 5.0978,  ..., 5.6961, 6.0216, 5.1740],
         [3.8007, 4.5707, 4.7085,  ..., 5.0778, 5.1114, 4.8330]],

        [[5.6484, 4.7915, 4.7952,  ..., 3.0939, 6.2386, 3.7801],
         [5.9052, 3.9795, 5.0659,  ..., 3.7589, 6.2453, 5.1648],
         [6.3313, 5.4387, 4.7213,  ..., 4.2219, 6.9555, 5.5326],
         ...,
         [5.5544, 4.7288, 4.0827,  ..., 3.4174, 5.9837, 3.7644],
         [6.6294, 5.4354, 4.9996,  ..., 4.4789, 6.5687, 5.1400],
         [6.1073, 4.8963, 5.1264,  ..., 4.0534, 6.3717, 4.8376]],

        [[6.3848, 8.5693, 6.2869,  ..., 7.0146, 6.5459, 7.2497],
         [5.3146, 6.3342, 4.6997,  ..., 5.3007, 4.3618, 5.3203],
         [3.5936, 5.4167, 3.2583,  ..., 4.1700, 4.5340, 4.

In [34]:
#Broadcasting
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))
print(x1-x2)
print(x1**x2)

tensor([[ 0.3111, -0.4472, -0.1223, -0.6935,  0.1713],
        [-0.4058, -0.2473,  0.4532, -0.0343,  0.4721],
        [ 0.0692, -0.1685,  0.0615,  0.0586,  0.1585],
        [-0.1978, -0.4518,  0.5761, -0.1747,  0.0062],
        [ 0.1908, -0.3196, -0.0401,  0.0734, -0.0551]])
tensor([[0.8783, 0.4504, 0.5974, 0.1450, 0.8091],
        [0.1914, 0.6384, 0.9158, 0.7935, 0.9679],
        [0.7414, 0.7093, 0.7453, 0.8697, 0.8016],
        [0.5330, 0.4459, 0.9542, 0.6743, 0.7038],
        [0.8140, 0.5719, 0.6751, 0.8816, 0.6597]])


In [39]:
sum_x = torch.sum(x,dim=0)
values,indices = torch.max(x,dim=0)
values,indices = torch.min(x,dim=0)
abs_x = torch.abs(x)
z = torch.argmax(x,dim=0)
mean_x= torch.mean(x.float(),dim=0)
eq = torch.eq(x,y)
so,indices= torch.sort(y,dim=0,descending=False)
cl = torch.clamp(x,min=0)
print(sum_x,values,indices,abs_x,z,mean_x,eq,so,cl,sep='\n')

tensor(6)
tensor(1)
tensor([0, 1, 2])
tensor([1, 2, 3])
tensor(2)
tensor(2.)
tensor([False, False, False])
tensor([4, 5, 6])
tensor([1, 2, 3])


In [43]:
batch_size= 10
features = 25
x = torch.rand(batch_size,features)

print(x.shape)
print(x[0].shape)
print(x[:,0])
print(x[2,0:10])

x= torch.arange(10)
indices= [3,4,7]
print(x[indices])

torch.Size([10, 25])
torch.Size([25])
tensor([0.2201, 0.4017, 0.0419, 0.3441, 0.2275, 0.6212, 0.4045, 0.7572, 0.5486,
        0.6743])
tensor([0.0419, 0.4315, 0.2126, 0.4223, 0.7176, 0.1342, 0.8823, 0.1316, 0.5120,
        0.9428])
tensor([3, 4, 7])


In [48]:
x= torch.arange(10)
print(x[(x>2) | (x>8)])
print(x[(x>2) & (x>8)])
print(x[(x>2) ^ (x>8)])
print(x[x.remainder(2)==0])

tensor([3, 4, 5, 6, 7, 8, 9])
tensor([9])
tensor([3, 4, 5, 6, 7, 8])
tensor([0, 2, 4, 6, 8])


In [54]:
print(torch.where(x>5,x,x*2))
print(torch.tensor([0,0,1,2,2,3,4]))
print(x.ndimension())
print(x.numel())

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 0, 1, 2, 2, 3, 4])
1
10


In [56]:
#Reshaping
x= torch.arange(9)
x_3x3 = x.view(3,3)
print(x_3x3)
x_3x3 = x.reshape(3,3)
print(x_3x3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [65]:
batch = 64
x=torch.rand(batch,2,5)

z = x.permute(0,2,1)
print(x.shape,' --> ',z.shape)

x = torch.arange(10)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)
x =torch.arange(10).unsqueeze(0).unsqueeze((1))
print(x.shape,x.squeeze(1).shape)

torch.Size([64, 2, 5])  -->  torch.Size([64, 5, 2])
torch.Size([1, 10])
torch.Size([10, 1])
torch.Size([1, 1, 10]) torch.Size([1, 10])
